In [1]:
#import numpy library

import numpy as np

In [2]:
# create a 1-d array using a list

array_1d = np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]


In [3]:
print(type(array_1d))

<class 'numpy.ndarray'>


In [4]:
# create a 2-d array using two lists

array_2d = np.array([[2,3],[4,5]])

In [5]:
print(array_2d)

[[2 3]
 [4 5]]


# why numpy is superior to conventional list or comprehension

In [6]:
list1=[1,2,3,4,5]
list2 =[6,7,8,9,10]


product_list = list(map(lambda x,y : x*y , list1,list2))
print(product_list)


[6, 14, 24, 36, 50]


In [7]:
#numpy way of doing it

array_1 = np.array(list1)
array_2 = np.array(list2)
array_3 = array_1*array_2
print(array_3)

[ 6 14 24 36 50]


In [8]:
# square a list

list_squared = [i**2 for i in list1]

In [9]:
list_squared

[1, 4, 9, 16, 25]

In [10]:
#squaring in numpy

array_squared = array_1**2

In [11]:
print(array_squared)

[ 1  4  9 16 25]


In [12]:
array_from_tuple = np.array((1,2,3,4))

In [13]:
print(array_from_tuple)

[1 2 3 4]


In [14]:
type(array_from_tuple)

numpy.ndarray

# creating numpy arrays using inbuilt functions

In [15]:
#np.arange() is the equivalent of range()


numbers=np.arange(10,100,5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [16]:
#linspace

#array of 25 length between 15 and 18

np.linspace(15,18,25)

array([15.   , 15.125, 15.25 , 15.375, 15.5  , 15.625, 15.75 , 15.875,
       16.   , 16.125, 16.25 , 16.375, 16.5  , 16.625, 16.75 , 16.875,
       17.   , 17.125, 17.25 , 17.375, 17.5  , 17.625, 17.75 , 17.875,
       18.   ])

In [17]:
# create an array of 5*3 matrix

array_1=np.ones((5,3))

In [18]:
array_1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   